/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUI.java
 *
 * Created on 22/12/2011, 9:07:40 PM
 */
package it.holiday69.phpwebserver.ui;

import it.holiday69.phpwebserver.model.Model;
import it.holiday69.tinyutils.ExceptionUtils;
import java.awt.Desktop;
import java.net.URI;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author fratuz610
 */
public class MainUI extends javax.swing.JFrame {

  private final Model _model = Model.getInstance();
  private static final Logger log = Logger.getLogger(MainUI.class.getSimpleName());
  
  /** Creates new form MainUI */
  public MainUI() {
    initComponents();
    
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jInfoLabel.setText("<html>Web Server started at<br/> http://127.0.0.1: " + _model.configObject.httpPort + "/</html>");
      }
    });
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOpenWebInterfaceBtn = new javax.swing.JButton();
        jExitBtn = new javax.swing.JButton();
        jInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PhpWebServer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jOpenWebInterfaceBtn.setText("Open Web Interface");
        jOpenWebInterfaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenWebInterfaceBtnActionPerformed(evt);
            }
        });

        jExitBtn.setText("Exit");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBtnActionPerformed(evt);
            }
        });

        jInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfoLabel.setText("Web Server started at 127.0.0.1:9080");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInfoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jOpenWebInterfaceBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jExitBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOpenWebInterfaceBtn)
                    .addComponent(jExitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jOpenWebInterfaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenWebInterfaceBtnActionPerformed
    if (Desktop.isDesktopSupported()) {
      Desktop desktop = Desktop.getDesktop();
      if(desktop.isSupported(Desktop.Action.BROWSE)) {
        try {
            URI uri = new URI(_model.configObject.startupURL);
            desktop.browse(uri);
        } catch(Exception ioe) {
            log.severe("Unable to browse to core interface because: " + ExceptionUtils.getFullExceptionInfo(ioe));
        }
      }
    }
  }//GEN-LAST:event_jOpenWebInterfaceBtnActionPerformed

  private void jExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBtnActionPerformed
    _model.notifyShutdown();
  }//GEN-LAST:event_jExitBtnActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    _model.notifyShutdown();
  }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExitBtn;
    private javax.swing.JLabel jInfoLabel;
    private javax.swing.JButton jOpenWebInterfaceBtn;
    // End of variables declaration//GEN-END:variables
}
