/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUI.java
 *
 * Created on 22/12/2011, 9:07:40 PM
 */
package it.holiday69.phpwebserver.ui;

import it.holiday69.phpwebserver.model.Model;
import it.holiday69.phpwebserver.task.WriteConfigTask;
import it.holiday69.phpwebserver.utils.IconUtils;
import it.holiday69.tinyutils.ConversionUtils;
import java.io.File;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author fratuz610
 */
public class SettingsUI extends javax.swing.JFrame {

  private final Model _model = Model.getInstance();
  private static final Logger log = Logger.getLogger(SettingsUI.class.getSimpleName());
  
  private MainUI _mainUI;
  
  private final ExecutorService _privateExecutorService = Executors.newSingleThreadExecutor();
  
  /** Creates new form SettingsUI */
  public SettingsUI() {
    
    initComponents();
    
  }
  
  public SettingsUI(MainUI mainUI) {
    _mainUI = mainUI;
    
    try {
      IconUtils.associateIcons(this, "/php-ico-32.png", "/php-ico-48.png", "/php-ico-64.png", "/php-ico-128.png", "/php-ico-256.png");
    } catch(Throwable th) {
      log.warning("Unable to associate icons to the SettingsUI window because: " + th.getMessage());
    }
    
    SwingUtilities.invokeLater(new Runnable() {

      @Override
      public void run() {
        _mainUI.setEnabled(false);
        jHttpPortTxt.setText("" + _model.configObject.httpPort);
        jFcgiPortTxt.setText("" + _model.configObject.fastCGIPort);
        jWwwFolderTxt.setText("" + _model.configObject.wwwFolder);
      }
    });
    
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFolderChooser = new javax.swing.JFileChooser();
        jUpdateBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jInfoLabel = new javax.swing.JLabel();
        jHttpPortTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFcgiPortTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jWwwFolderTxt = new javax.swing.JTextField();
        jBrowseBtn = new javax.swing.JButton();
        jErrorTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PhpWebServer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jUpdateBtn.setText("Update");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });

        jCancelBtn.setText("Cancel");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jInfoLabel.setText("Current Settings");

        jHttpPortTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jHttpPortTxt.setText("9080");

        jLabel1.setText("Http Port");

        jLabel2.setText("Fcgi Port");

        jFcgiPortTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFcgiPortTxt.setText(" 9081");

        jLabel3.setText("Www Folder");

        jWwwFolderTxt.setEditable(false);
        jWwwFolderTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jWwwFolderTxt.setText("c:\\ywc\\tools");

        jBrowseBtn.setText("Browse");
        jBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseBtnActionPerformed(evt);
            }
        });

        jErrorTxt.setForeground(new java.awt.Color(255, 0, 0));
        jErrorTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jErrorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUpdateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jHttpPortTxt)
                            .addComponent(jWwwFolderTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jFcgiPortTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrowseBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHttpPortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFcgiPortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWwwFolderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBrowseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateBtn)
                    .addComponent(jCancelBtn)
                    .addComponent(jErrorTxt))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
    
    
    int httpPort = ConversionUtils.stringToInt(jHttpPortTxt.getText());
    int fcgiPort = ConversionUtils.stringToInt(jFcgiPortTxt.getText());
    String wwwFolder = jWwwFolderTxt.getText();
    
    if(httpPort < 1 || httpPort > 65000) {
      updateErrorText("Invalid http port number");
      return;
    }
    
    if(fcgiPort < 1 || fcgiPort > 65000) {
      updateErrorText("Invalid fcgi port number");
      return;
    }
    
    if(httpPort == fcgiPort) {
      updateErrorText("The http and fcgi ports cannot be the same");
      return;
    }
    
    boolean settingsUpdated = false;
    
    if(fcgiPort != _model.configObject.fastCGIPort) settingsUpdated = true;
    if(httpPort != _model.configObject.httpPort) settingsUpdated = true;
    if(!_model.configObject.wwwFolder.equals(wwwFolder)) settingsUpdated = true;
    
    _model.configObject.fastCGIPort = fcgiPort;
    _model.configObject.httpPort = httpPort;
    _model.configObject.wwwFolder = wwwFolder;
    
    if(settingsUpdated) {
      _privateExecutorService.submit(new WriteConfigTask());
      _model.logToScreen("Settings updated, restarting server");
      _model.notifyRestart();
    }
    
    fullDispose();
    
  }//GEN-LAST:event_jUpdateBtnActionPerformed

  private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed

    fullDispose();
  }//GEN-LAST:event_jCancelBtnActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    fullDispose();
  }//GEN-LAST:event_formWindowClosing

  private void fullDispose() {
    
    final SettingsUI thisWindowRef = this;
    
    _privateExecutorService.shutdownNow();
    
    SwingUtilities.invokeLater(new Runnable() {

      @Override
      public void run() {
        thisWindowRef.dispose();
        _mainUI.setEnabled(true);
      }
    });
  }
  
  private void updateErrorText(final String errorStr) {
    
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jErrorTxt.setText(errorStr);
      }
    });
  }
  
  private void jBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseBtnActionPerformed
    
    jFolderChooser.setCurrentDirectory(new File(jWwwFolderTxt.getText()));
    jFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int returnVal = jFolderChooser.showOpenDialog(this);
    
    if(returnVal != JFileChooser.APPROVE_OPTION)
      return;
    
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jWwwFolderTxt.setText(jFolderChooser.getSelectedFile().getAbsolutePath());
      }
    });
    
  }//GEN-LAST:event_jBrowseBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrowseBtn;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JLabel jErrorTxt;
    private javax.swing.JTextField jFcgiPortTxt;
    private javax.swing.JFileChooser jFolderChooser;
    private javax.swing.JTextField jHttpPortTxt;
    private javax.swing.JLabel jInfoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jUpdateBtn;
    private javax.swing.JTextField jWwwFolderTxt;
    // End of variables declaration//GEN-END:variables
    
}
